gitlabUrl: https://git.datacentric.kr

#certsSecretName: gitlab-runner-certs

runnerRegistrationToken: glrt-QT5bQRx8fLuoYq5SyVot

concurrent: 3

runners:
  ## Specify one or more imagePullSecrets
  ##
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
#  imagePullSecrets: harbor.dev.dc

  ## Run all containers with the privileged flag enabled
  ## This will allow the docker:stable-dind image to run if you need to run Docker
  ## commands. Please read the docs before turning this on:
  ## ref: https://docs.gitlab.com/runner/executors/kubernetes.html#using-docker-dind
  ##
  privileged: true
  #secret: gitlab-runner-secret

rbac:
  create: true
  
