apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"meta.helm.sh/release-name":"gitlab","meta.helm.sh/release-namespace":"gitlab","pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes"},"creationTimestamp":"2022-08-12T01:15:16Z","finalizers":["kubernetes.io/pvc-protection"],"labels":{"app":"minio","app.kubernetes.io/managed-by":"Helm","chart":"minio-0.4.3","heritage":"Helm","release":"gitlab"},"name":"gitlab-minio","namespace":"gitlab","resourceVersion":"5727326","uid":"ef951ef0-e496-47f2-ab6b-85965d15a82e"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"selector":{"matchLabels":{"type":"minio"}}},"status":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"100Gi"},"phase":"Bound"}}
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2022-08-12T03:58:17Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-0.4.3
    heritage: Helm
    release: gitlab
  name: gitlab-minio
  namespace: gitlab
  resourceVersion: "5767637"
  uid: f3fe2a5f-8921-41ba-bbdb-e04d2405daad
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: "gitlab-minio"
  volumeMode: Filesystem
status:
  phase: Lost
