---
# https://hub.docker.com/_/mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sfs # 배포 이름
  labels:
    app: mongodb # 배포 이름
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb # 배포 이름
  template:
    metadata:
      labels:
        app: mongodb # 배포 이름
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/hostname # worker03~06에만 raid가 설정되어있으므로 해당 노드으로 지정
#                operator: In
#                values:
#                - worker03
#                - worker04
#                - worker05
#                - worker06
      containers:
        - name: mongodb  # 컨테이너 이름
          image: "docker.io/mongo:4.4" # 이미지명 (반드시 4.4 이하의 버전을 사용해야함. 5.0부터는 Sandy Bridge 이상의 CPU만 지원하는데, 사내 서버의 CPU는 미지원)
          imagePullPolicy: IfNotPresent
          env:
                      
            # mongodb 관리자 계정 이름 지정
            # 권장은 kubernetes 에서 Secret 으로 관리하는 것이지만 편의상 직접 설정함
            - name: MONGO_INITDB_ROOT_USERNAME 
              value: admin

            # 패스워드 보안을 위하여 Secret 객체를 활용
            # 쿠버네티스에서의 패스워드(Secret) 생성 명령어
            # kubectl create secret generic database-secret -n dev --from-literal=root-password=$(echo '비밀번호' | base64)
            - name: MONGO_INITDB_ROOT_PASSWORD # 패스워드 보안을 위하여 Secret 객체를 활용
              valueFrom: 
                secretKeyRef: # secret 리소스인 database-secret에 저장된 root-password의 값을 불러옴
                  name: database-secret
                  key: root-password

           # - name: MONGO_INITDB_ROOT_PASSWORD  # 패스워드 직접 명시도 가능  
           #   value: "1234!" 

          ports: # 컨테이너 내부에서 사용하는 포트 명시
              - name: db-port
                containerPort: 27017
                protocol: TCP
          volumeMounts: # 영구 저장할 볼륨 (디렉토리) 설정
            - name: data-volume # 위에서 명시한 볼륨명 지정
              mountPath: /data/db
            # - name: config-file # 설정이 필요한 경우
            #   mountPath: /etc/mongo/mongod.conf # 실제로 사용시 configmap 으로 만들어서 mount할 것
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 10Gi
      
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # 서비스 이름
spec:
  selector:
    app: mongodb # 연결할 Deployment의 이름
  type: LoadBalancer # 서비스 유형 LoadBalancer는 172.17.250.100 ~ 172.17.250.150 중에서 자동 할당하도록 설정되어있음
  ports:
  - name: service-port
    port: 27017 # Pod 내부에서 사용하는 포트. 실제 할당된 아이피는 $(kubectl get service -n dev) 로 조회
    protocol: TCP
  loadBalancerIP: 172.17.250.113
  # externalIPs: # 필요한 경우 아이피 지정 가능 (단, 로드밸런서의 아이피 설정 범위에 한해서)
  #   - 172.17.250.120
