apiVersion: v1
kind: PersistentVolume
metadata:
  name: handh-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server: kube-nfs
    path: "/home/nfs/handh_1"