apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handh-pvc-1
spec: 
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi