apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins-pvc
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
