---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-postgresql
  labels:
    type: postgresql
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: kube-nfs
    path: "/home/nfs/airflow/postgresql"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags
  labels:
    type: dags
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: kube-nfs
    path: "/home/nfs/airflow/dags"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    type: logs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: kube-nfs
    path: "/home/nfs/airflow/logs"
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-redis
  labels:
    type: redis
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: kube-nfs
    path: "/home/nfs/airflow/redis"
---

