apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    release: airflow
    tier: airflow
  name: airflow-dags-pvc
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-dags-pvc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    release: airflow
    tier: airflow
  name: airflow-logs-pvc
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-logs-pvc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
