apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: airflow
    app.kubernetes.io/name: postgresql
    role: primary
  name: data-airflow-postgresql-0
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-postgresql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: dags
    release: airflow
    tier: airflow
  name: dags-airflow
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-dags
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: redis
    release: airflow
    tier: airflow
  name: redis-db-airflow-redis-0
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-redis
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: worker
    release: airflow
    tier: airflow
  name: logs-airflow-worker-0
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-logs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: redis
    release: airflow
    tier: airflow
  name: redis-db-airflow-redis-0
  namespace: airflow
spec:
  storageClassName: "manual"
  volumeName: airflow-redis
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
