apiVersion: v1
data:
  secretkey: Z1VKb2MvK1Ira3BkUmllcVptQnR6emsvT2dPa25xZi9qQ0I0d2kxbi9kazBqUktadytCdE5mejNmb1ZUV2RHaQpYTHZGRDdBNG84WG0rRW1JK3RFbk5IMnlOTmx4cjEvN3NHMTI4b21KRUgxMUdFNmVYVExpalNqOUhqRk1kbTZMCm9aOUZMQnZsSHlHdVJZMlk4R0IvaHRMS1RlRUxoeXhWMkl1dlRPTE4vcFE9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
